services:
  db:
    image: postgres
    container_name: demo_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - /home/ubuntu/data/demo:/var/lib/postgresql/data
  api:
    build: ./api
    container_name: demo_api
    restart: always
    depends_on:
      - db
  front:
    build: ./front
    container_name: demo_front
    restart: always
  proxy:
    image: nginx
    container_name: demo_proxy
    restart: always
    ports:
      - "5000:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
